INSERT INTO `consumables` (`id`, `name`, `type`) VALUES
(1, 'Ancientberry', 'Rare Component'),
(2, 'Astralune', 'Rare Component'),
(3, 'Auraglass', 'Standard'),
(4, 'Bluemaple', 'Standard'),
(5, 'Echoberry', 'Standard'),
(6, 'Essentia', 'Rare Component'),
(7, 'Heartwater', 'Standard'),
(8, 'Lifepowder', 'Standard'),
(9, 'Meadowgem', 'Standard'),
(10, 'Moonruby', 'Standard'),
(11, 'Riverstone', 'Standard'),
(12, 'Seamelon', 'Standard'),
(13, 'Skypollen', 'Standard'),
(14, 'Starweave', 'Rare Component'),
(15, 'Sunnyseed', 'Standard'),
(16, 'Timeshard', 'Standard'),
(17, 'Treescent', 'Standard'),
(18, 'Watervine', 'Standard'),
(19, 'Whiteroot', 'Standard'),
(20, 'Wood', 'Building Material'),
(21, 'Stone', 'Building Material'),
(22, 'Metal', 'Building Material'),
(23, 'Supplies', 'Building Material'),
(25, 'Mystic Dew', 'Tree'),
(26, 'Gemstone', 'Tree'),
(27, 'Tree Seeds', 'Tree'),
(28, 'Spirit Stones', 'Tree'),
(29, 'Earth Orb', 'Orb'),
(30, 'Fire Orb', 'Orb'),
(31, 'Water Orb', 'Orb'),
(32, 'Wind Orb', 'Orb'),
(33, 'Earth Shard', 'Shard'),
(34, 'Fire Shard', 'Shard'),
(35, 'Water Shard', 'Shard'),
(36, 'Wind Shard', 'Shard'),
(37, "Coins", "Other");
