-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               10.9.8-MariaDB-1:10.9.8+maria~ubu2204 - mariadb.org binary distribution
-- Server OS:                    debian-linux-gnu
-- HeidiSQL Version:             12.8.0.6908
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping data for table uc_archive.exploration_areas: ~11 rows (approximately)
INSERT IGNORE INTO `exploration_areas` (`id`, `name`, `slug`, `description`, `accomplishments`) VALUES
	(1, 'The Great Plains', 'the-great-plains', 'The Great Plains are huge grasslands that cover much of the world. The rolling prairies extend in places from the heat of the equator up to the arctic tundra. This variety in climate is home to a vast array of wild life and magical creatures. You could spend years wandering the Great Plains and still discover new things every day.', 0),
	(2, 'Sargasso', 'sargasso', 'Sargasso is what the natives call their largest body of water. It is a vast sea that sits between the Great Plains and Silva, the forest lands. It is more than just that however. There are a number of lakes scattered around the world that are so large they seem small seas in themselves. There are ponds, rivers, extensive swamps and many other watery areas. By the strange magic of this world, all water areas somehow connect to one another. With enough creativity and a bit of magic you can travel from any water location to any other throughout the entire world.', 0),
	(3, 'Silva', 'silva', 'Silva, the great forest is actually a number of nature sites all linked together. The inhabitants of this world have great respect for nature and much of the planet is still wild forest, rolling grasslands, or vast sea. It\'s possible to walk all the way around the world and never leave the wild lands. The forests has young forested areas, wild jungle, ancient oak forests, and magical hidden places so old and well protected that only the treants know about them. It is a vast, mysterious, and beautiful place full of wonders of all kinds.', 15),
	(4, 'New Atlantis', 'new-atlantis', 'New Atlantis is the largest city in this world. It is a vast, varied, and very curious metropolis with an unbelievable number and variety of inhabitants. Humans, elves, gnomes, Fae, trolls, giants, dragons, foxes, bears, wolves, bunnies, and a whole lot more call New Atlantis home. Every type of unicreature is found there as well. And anything you need or want, magical, mundane, beautiful or plain, you can find it there.', 50),
	(5, 'The Mountains', 'the-mountains', 'There are a number of mountainous areas throughout the world. The natives of each area give them unique and wonderful names in many strange languages. There are small mountain ranges and huge ancient peaks full of mystery. The best known mountain areas are the Spine of the World, the Ogre\'s teeth, and Dragon Spire.', 100),
	(6, 'Old City', 'old-city', 'Like any major metropolis, New Atlantis has been expanded and rebuilt countless times. Entire parts of the city have been abandoned, forgotten, reclaimed and restructured. This has led to a second city, located under the ground of New Atlantis. This place is called Old City, and many unique creatures make their home there.', 150),
	(7, 'Red Sand', 'red-sand', 'Far from the mainland, almost on the other side of Esmelda, lies the island of Red Sand. Red Sand, so named for the bright red color of its earth, is a highly magical place and the veil between the spirit world and the material world is thin here. Red Sand offers a wide variety of creatures, some who are not unlike their mainland cousins, and others who look strange and wondrous indeed. Caretakers who set foot on Red Sand quickly fall in love with this land and its wonderful creatures, and many believe that the island, with its strange red earth, is the living heart of Esmelda. Only caretakers who have a deep and true understanding of their unicreatures and through them, Esmelda, can reach Red Sand. To all others, the island is like a mirage, always fading on the horizon.', 200),
	(8, 'Life Tree', 'life-tree', 'At the heart of Silva Forest stands the massive Life Tree, dwarfing mountains and the already impressive Silvan trees. From its branches hang a myriad of different seeds and botanists often speculate that Life Tree was the first tree on Esmelda, with all other trees descendant from it. What most do not know is that the Life Tree is a sentient creature that once partnered with Jody DeSilva (even this legendary caretaker would not dare to say she \\"owned\\" Life Tree, preferring to see their relationship as a partnership instead).\n\nThe Life Tree is so vast that most human minds cannot comprehend it as only one tree, which is why it is often referred to as "The Treetops." And indeed, the treetop is where most activities go on in Life Tree. Whilst the bottom of each leaf radiates light, providing the layer below it with the light needed to grow, the canopy is so dense that living there is difficult. As the leaves at the base and top of the tree are a little less dense, most creatures live in one of these two places, with most of them preferring the treetop.', 250),
	(9, 'Cloud City', 'cloud-city', 'High above Esmelda, almost in a different world, rises Cloud City. Held afloat with amazing steam technology, its high-domed buildings with elegant spires rest on rocks amidst the clouds. To the casual onlooker, Cloud City is all brass, copper and steam. More dedicated visitors quickly discover it\'s so much more than that. Cloud City is a way of life that permeates everything, right down to the way its inhabitants see, feel and think. It\'s about making the impossible possible, elegant beauty combined with raw power and above all, it\'s about passion for new experiences.\n\n			Cloud City is one of the few places where one can encounter dwarfs outside their underground halls and while the other dwarfs consider them \'old fashioned,\' their applications and discoveries in the field of steam technology astounds even the high-tech inhabitants of Old City.\n\n			There are many ways into Cloud City, but the brass ornithopter (an amazing ride even if it crashes - and there\'s a fifty percent chance it will!) and stepping stones leading from Life Tree are the most popular by far. So welcome and enjoy your stay in Cloud City: even the sky is not the limit here!', 300),
	(10, 'Skyland', 'skyland', 'To the West of Cloud City lies Skyland, a series of floating islands high above the ground. Scholars studying the history of Esmelda believe that Skyland and Cloud City were once part of one enormous continent held aloft by thermal winds. For reasons yet unknown the continent shattered into thousands of smaller islands that slowly drifted apart on the currents.\n\n			The islands of Skyland are eclectic and strange. Some float so high above the ground that they’re covered in permafrost, whereas others are visited by warm winds that create an eternal summer. Few people make their home on Skyland as, apart from the zeppelin service to and from Cloud City, there is no transport system connecting the islands – anyone wanting to explore here must do so under their own power.', 350),
	(11, 'Hephland', 'hephland', 'Hephasteus, the well-known owner of New Atlantis Plaza, is the richest man on Esmelda by far. The fee he asks for distributing eggs to and from the Plaza is minimal: just enough to cover expenses and build a small reserve in case transportation costs go up. Over the years, however, the reserve kept building until it became a big reserve. Huge, actually. Not wanting to simply keep the money for himself, Hephasteus started thinking of other ways to use it. Finally he decided on Hephland: a place where Caretakers AND creatures can go to relax.\n\n			Hephland lies on one of the most Southern points of Skyland, just barely extending over Red Sand. It is housed on one of the biggest floating Islands – not counting Cloud City, of course – and can safely hold thousands of visitors at a time. Hephland is divided into three parts: an amusement park, a resort area and Hephasteus\' mansion. The amusement park features every known ride, in addition to several of Hephasteus\' own design, whilst the resort offers every possible luxury. The mansion is Hephasteus\' home when he\'s not in New Atlantis, though most of it is open to visitors too. It consists of a huge house with grounds, a swimming pool and tennis court. All in all, Hephland is everything anyone could want for a wonderful vacation.', 400);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
