-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               10.9.8-MariaDB-1:10.9.8+maria~ubu2204 - mariadb.org binary distribution
-- Server OS:                    debian-linux-gnu
-- HeidiSQL Version:             12.8.0.6908
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping data for table uc_archive.shop_transactions: ~0 rows (approximately)
INSERT IGNORE INTO `shop_transactions` (`id`, `shop_category_id`, `rewardable_type`, `rewardable_id`, `title`, `amount`, `short_description`, `description`) VALUES
	(1, 1, 'App\\Models\\Item', 12, 'Aurora\'s Frost', 1, 'This cyrogenic freeze spray will freeze a creature or egg in its current form. It cannot evolve, be trained, do combat, be used in accomplishments, or count toward your egg limit.', 'With a puff of smoke and a magical icicle imbued by Aurora, Hephasteus extracts a mystical spray and bottles it up for you'),
	(2, 1, 'App\\Models\\Item', 36, 'Reheated', 1, 'This Defrosting Torch will reverse the effects of the Cryogenic Spray used on a creature or egg.', 'With a puff of smoke and a hint of cinnamon, the ingredients turn into a Defrosting Spray!'),
	(3, 2, 'App\\Models\\Consumable', 1, 'Ancientberry', 1, NULL, 'The very essence of time condenses together around the sunnyseeds, awakening thousands of years of power within the group.'),
	(4, 2, 'App\\Models\\Consumable', 2, 'Astralune', 1, NULL, 'Light gathers in the riverstone atop the pile of components and there is a blinding flash. You see the afterimage of the moon before the light fades and an Astralune rests in the dim room before you.'),
	(5, 2, 'App\\Models\\Consumable', 14, 'Starweave', 1, NULL, 'You sprinkle auraglass over the pile of components and as you watch, they seem to melt and fuse together. The seamelon crystallizes and splits open, revealing a Starweave in its center before the halves vanish into starlight.'),
	(6, 2, 'App\\Models\\Consumable', 6, 'Essentia', 1, NULL, 'The pile of components focuses together, and the smell of raspberries overwhelms you as smoke starts to form from the pile. You feel as though a great sigh was released as the smoke clears away and an Essentia is left in its place.'),
	(7, 3, 'App\\Models\\Consumable', 20, 'Self-slicing Tree', 2, NULL, 'A mighty tree grows before you in an instant, then falls apart into lumber.'),
	(8, 3, 'App\\Models\\Consumable', 21, 'Petrification', 1, NULL, 'You grind the timeshard and carefully apply it to the whiteroot. An ancient incantation causes the timeshard to age the root at an amazing pace... petrifying it and producing usable stone.'),
	(9, 3, 'App\\Models\\Consumable', 22, 'Forgeria', 1, NULL, 'Normally it takes millennia for metal to form deep in the earth\'s crust. Using the magic of lifepowder on a riverstone, you wake in it the essence of metal ore.'),
	(10, 4, 'App\\Models\\Item', 35, 'Modestius', 1, 'The Normalize potion will turn your Noble or Exalted back into a regular creature. Be careful with its use!', 'Making a small fire under your miniature cooking pot, you begin to heat up some echoberries and watervine. When the water reaches boiling, you toss in a sprinkle of auraglass. After letting it stew until the fire dies, you pour the resulting mixture into one of your potion containers.'),
	(11, 4, 'App\\Models\\Item', 33, 'Elixir of Nobility', 1, 'The Elixir of Nobility will rebirth a creature with 500 or more care points as a noble!', 'Some magic happens. Don\'t ask me, it was 6 in the morning when I was typing this.'),
	(12, 4, 'App\\Models\\Item', 34, 'Elixir of Exaltation', 1, 'The Elixir of Exalted will rebirth a noble creature with 1,000 or more care points as an exalted!', 'Some magic happens. Don\'t ask me, it was 6 in the morning when I was typing this.'),
	(13, 1, 'App\\Models\\Item', 2, 'Female Gen-X', 1, 'This genetically-mutating drink will alter a male creature to female. Giving it to female creatures does nothing.', 'In a small mixing pot, you add in the echoberries, some crushed seamelon, and a sprinkle of lifepowder and heartwater and begin to stir clockwise. After a good while, you have a goopy mixture, which you spoon into a potion container.'),
	(14, 1, 'App\\Models\\Item', 1, 'Male Gen-X', 1, 'This genetically-mutating drink will alter a female creature to male. Giving it to male creatures does nothing.', 'In a small mixing pot, you add in the echoberries, some crushed seamelon, and a sprinkle of lifepowder and heartwater and begin to stir counter-clockwise. After a good while, you have a goopy mixture, which you spoon into a potion container.'),
	(15, 4, 'App\\Models\\Item', 37, 'Refresh Potion', 1, 'The Refresh Potion restores a little bit of your combat, training, and exploring energy.', 'You crush up some Ancientberries and mix in some Essentia in your container, sprinkling a dose of timeshard through a Starweave. It bubbles as you hold the Astralune over it, reshaping it into a very rejuvenating drink.'),
	(16, 4, 'App\\Models\\Item', 38, 'Vigor Potion', 1, 'The Vigor Potion will restore some of your exploring energy, up to 25 points.', 'Holding a funnel of watervine over a potion, you slowly pour water down into a beaker and leave it to take in sunlight through a Starweave.'),
	(17, 4, 'App\\Models\\Item', 39, 'Moxie Potion', 1, 'The Moxie Potion will restore some of your combat energy, up to 15 points.', 'You imbue the proper berries with Essentia and quickly toss it into a beaker to watch as the mixture liquefies before you.'),
	(18, 4, 'App\\Models\\Item', 40, 'Vitality Potion', 1, 'The Vitality Potion will restore some of your training energy, up to 25 points.', 'You dip an Astralune into a large bowl of auraglass powder and run Starweave through it until the mixture is a healthy mystic glow.'),
	(19, 5, 'App\\Models\\Creature', 53, 'Beloved Egg', 1, 'This spell summons a recently-created cupid egg to your location.', 'You prepare a large arch that reaches outward over an elegant bowl designed of Astralune and Moonrubies. As the warmth of the sun passes over the bowl, you focus the energies over the bowl with a Starweave lens until the Ancientberries begin to warm up and melt into the bowl. The bowl begins to glow with a pulsing red aura until you hear a gentle pop. The aura fades, leaving behind a beloved red egg in the bowl.'),
	(20, 5, 'App\\Models\\Creature', 71, 'Luck Vision', 1, 'This spell temporarily alters a user\'s vision to see luck instead of light, and can follow it to a hidden Clover Egg.', 'You prepare a mat of watervine leaves with scattered Ancientberries on them in a ritual circle of Astralunes. You ground a rod of metal into the ground and hold onto it while sprinkling some Essentia over the circle. Sparks begin to charge up from the circle. A static charge begins to connect to you, as you ground the excess through the metal. Within seconds, your sight begins to shift into a strange whirl of unusual colors and the static ends. You can clearly see a path of luck, and begin to follow it. As luck would have it, it takes only a few quick seconds to locate a hidden egg nearby.'),
	(21, 5, 'App\\Models\\Creature', 112, 'Orchestrate', 1, 'This spell enables the user to initiate a fully-orchestrated musical in any urban area, resulting in the grand finale of a newly discovered Waddles Egg being held up in the center of a giant parade of caretakers and creatures.', 'You drink a special concoction that you prepared, which begins to take effect. You can feel yourself developing the communication ability of Waddles. You begin to vocalize a very precise and elaborate musical to everyone in the area, and within seconds, an entire parade of makeshift instruments and singing has begun. Dancers begin gracefully spinning through the streets as their creatures weave beautiful decorations through the air and drop confetti. The music becomes increasingly grandiose as a fully-orchestrated wave of caretakers and creatures collaborate into the center of a large road, and the music makes an epic finish as a brand-new Waddles Egg is held up in the center for you.'),
	(22, 1, 'App\\Models\\Item', 41, 'Profession Scroll', 1, 'This spell produces a Profession Scroll, which is used to change your class.', 'You sit down at dawn before the open horizon and place your components in a circle around you. As the sun gleams down over you, you chant a series of mystic words and splash an Ancientberry onto the page, revealing a blessed letter that will guide you to achieving a great transformation.'),
	(23, 5, 'App\\Models\\Creature', 97, 'Hide and Seek', 1, 'This spell is cast in a location with many hiding places and leads the user on a merry search, resulting in a Twitch egg.', 'You lay the components by a tree in a New Atlantis park.  You recite the incantation but nothing happens immediately and while waiting, you doze off.  When you wake, you catch a brief glimpse of a cotton tail before you see all your components are gone!  A basket sits beside you and there seems to be a meadowgem near an adjacent tree.  Nestled in its branch is one of your missing Ancientberries!   You painstakingly follow the trail and search for each component, collecting them in the basket.  When you add the last one, the basket twitches and you catch the Twitch egg trying to hop out.'),
	(24, 5, 'App\\Models\\Creature', 128, 'Growth Spurt', 1, 'This spell causes a Daisy Egg to spurt up from the ground in any area of the forest where you cast the spell.', 'You sprinkle the Essentia powder around a circular pattern in the woods and evenly place four Starweave around it. You cover the inside of the circle with treescent, and charge up some astralune with energy and drop them in the center. It takes a little, but the ground beneath you begins to quiver slightly, and the top of an egg begins to peak out of the treescent covering. It slowly peeks out completely, leaving a Daisy Egg.'),
	(25, 3, 'App\\Models\\Consumable', 23, 'Scotty\'s Toolbox', 1, NULL, 'You leave water, berries and some cheesecrackers under the sink. You hear a splash of water and when you look again, they\'re gone! In their place sits a toolbox.'),
	(26, 5, 'App\\Models\\Creature', 144, 'Drum Solo', 1, 'This spell enables the user to hear a wind song. As the caster accompanies the song on a specially enhanced drum, it attracts a Beeks egg.', 'You build a stage in Silva and sit in the center with your Essentia-embossed drum. You recite the spell and the breeze spins in the Astralune star around you, sounding the Starweave chimes above your head as you start to play to the wind song growing louder in your ear. As the song and your accompaniment crescendo, the wind whirls faster and your drum flashes to the rhythm you beat out. Finally, the music peaks and your drum burns incandescent. The next moment, everything is silent. You hear a clicking and lift up your now-ordinary drum to reveal a Beeks egg.'),
	(27, 5, 'App\\Models\\Creature', 172, 'Calling on the Deep', 1, 'Calling upon the powers of the deep ocean, you transport yourself to the area of the Muse colony where they will grant you one of their eggs.', 'You add the last of the seamelon and suddenly, the room starts filling up with water. It rises quickly and when it reaches the ceiling, you find yourself in the middle of the ocean. Dolphins and fish swim around you. Off in the far distance, you see large serpentine shapes gliding through the water. Then you notice a single Muse egg floating in the water before you. You reach out to take it and as your fingers close around it, the water drains away. You\'re back in your room, holding the egg while water still drips off various surfaces.'),
	(28, 5, 'App\\Models\\Creature', 181, 'The Light Lantern', 1, 'This spell takes you to the spirit world, where the spirit of things to come lives. This spirit will gift you with a Tsuru egg.', 'There\'s a flash of bright light as you add timeshard and you\'re temporarily blinded. When you see clearly again, you\'re standing on the shore of a vast lake. Lit lanterns fill the lake, forming a sea of light as far as you can see. Then, as suddenly as you appeared at the lake, you\'re back in your laboratory. The room is filled with the lanterns from your vision and one of them clearly stands out as you feel the life within reach out to you. Smiling, you reach to pick up the Tsuru egg before you.'),
	(29, 5, 'App\\Models\\Creature', 198, 'Masters of the Dance', 1, 'This spell creates a stage and calls forth a pair of dancers who will gift the caster with a Flamenco egg.', 'You carefully check the incantation for summoning a Flamenco egg again - you have gathered all the components and built the wooden stage the spells call for. You read the last part of the incantation aloud and soft music begins to play in the distance. A pair of Flamenco appear on the stage and, slowly and perfectly, start their heart-dance. Their every movement, right down to their breathing, is perfectly synchronized and you watch them in awe. When they finish their dance, they vanish again, leaving a Flamenco egg behind.'),
	(30, 5, 'App\\Models\\Creature', 214, 'Sweet Fruit Pie', 1, 'Combining the power of the arcane and the lure of freshly baked fruit pie, the caster calls forth a Kaylee egg.', 'You add the last of the fruits and sprinkle sweet sugar syrup on top of them. It looks wonderful and you set it to bake in the traditional wood oven. When you pull it out, the whole has transformed into a delicious pie. You\'re just about to take your first bite when a soft squee draws your attention - it comes from a small pumpkin egg sitting nearby. Although it has no eyes, you can feel it watching you and the pie intently and, on impulse, you offer it a slice. You feel the egg take a liking to you instantly.'),
	(31, 5, 'App\\Models\\Creature', 233, 'Uphill Journey', 1, 'With a sack of feed, the user climbs upon a self-propelled chariot to begin travels in search of a Plymouth egg.', 'You sit down in your elegant chariot, check your spell and cast the transmute. The Starweave and Astralune you selected for this jump to life and ribbon into a path before you.   The chariot begins to follow the path of its own accord.  It is a long journey but you are determined to continue and eventually, you find yourself in the woods. It looks deserted, but you feel you are being watched. The chariot rolls to a stop in a clearing and several Plymouth come out to greet you. You offer them a sunnyseed-auraglass mix and they feed happily. After they leave, you find a Plymouth egg left for you.'),
	(32, 5, 'App\\Models\\Creature', 237, 'The Cloud Gathering', 1, 'This mystical spell will transport you to the clouds, where you may gather a Perline egg out of season.', 'You carefully tie the Starweave and Astralune to a sitting perch you constructed of cedar wood. It\'s a large perch, human-sized in fact, and you carefully take place on it. You add extra Skypollen for more buoyancy and the perch slowly rises into the air. You carefully weave the Essentia into a spell that will carry you to the Perline clouds and protect you from the hardships of flight; after that, you literally sit and wait. The journey is unexpectedly swift and you find yourself surrounded by pristine white clouds and Perline eggs. Choosing carefully, you reach out to take one.'),
	(33, 5, 'App\\Models\\Creature', 245, 'Reminiscence', 1, 'The user spends an evening thinking about and reconnecting with the people in their life. The memories attract a Julian egg.', 'The room immediately cools around you after you read the spell.  You settle yourself on your couch in a nest of blankets to ward off the chill and start writing letters to your friends and family.  As you write, the components beside you start to dissolve, glittering in the air like snow.  It would be nice to enclose photos too, so you fetch a packet of them. Your intent to sort fades until you\'re just looking through them and as you become lost in your memories, you feel the brush of a ribbon against your cheek and look up to see a Julian egg perched on your shoulder.'),
	(34, 5, 'App\\Models\\Creature', 263, 'Follow that Egg', 1, 'The caster looks within themselves and is transported to the lake where Capricorn eggs first appeared.', 'You sit down and read the spell.  As you reflect on your goals and think of how to accomplish them, your components start to dust, forming a bubble around you, and you find yourself in a lake.  Old City gleams overhead, distorted through the water.  A flash of red and black catches your eye and you glimpse a little egg determinedly swimming to shore. You follow it and it races out of reach but you keep trying and once it\'s on shore, it waits just long enough. When you pick it up, you find yourself back home, Capricorn egg hiding in your shirt.'),
	(35, 5, 'App\\Models\\Creature', 259, 'Reality Manifested', 1, 'Harnessing the essence of reality itself, this spell calls forth a powerful Relity egg.', 'With trembling hands, you add the components to the stone egg you carved. Each component you use is valuable, containing the essence of life on Esmelda itself. When you\'re done, you softly imbue the egg with your breath, calling it to life. The stone becomes softer, yet somehow more solid and real. You smile as you realize that the spell worked - you\'ve succesfully consolidated reality into this precious egg.'),
	(36, 5, 'App\\Models\\Creature', 287, 'Fall in Reverse', 1, 'The caster climbs the highest nearby peak and creates a waterfall to transport to an area where Aquarius eggs are found.', 'You grind the components into dust and stir them into the water. It shines iridescent and when you read the spell, it shimmers turquoise. You see a goat-shaped cloud nearby and with the bowl carefully in hand, you follow it up to the top of the nearest mountain. You tip the bowl and strangely, the water doesn\'t fall down, but up, leading to a fluffy cloud above your head.  A strange symbol glows from within the cloud and then the teal stream spins around you, both cloud and water disappearing. The bowl you brought with you is transformed, and an Aquarius egg sits happily within its circumference.'),
	(37, 5, 'App\\Models\\Creature', 304, ' Guarded Steps', 1, 'The caster is brought to an area in Red Sand where they must cross a barrier.', 'You stir the crushed ingredients into the bucket slowly until they dissolve. Once they are, you recite the words and pour the bucket over your head.  When you shake the water from your eyes, you find yourself in an inlet by a stairway that leads deep into the water.  Two Aquarius study you carefully before they let you pass. You follow the staircase down, straight into the deep water, but with every step you take, you seem to be immersed in more than water.  It\'s not a staircase into water after all, but one into another world. Right at the last step, you find a Pisces egg flickering before you.'),
	(38, 5, 'App\\Models\\Creature', 315, 'Fireside Audience', 1, 'Consult a magical fire that may lead the caster to an Aries egg.', 'You think these directions look oddly straightforward, but you burn the ingredients and wait until the fire roars before whispering the incantation.  The fire seems to snap and burn brighter until a symbol manifests in the flames.  You study the symbol and it\'s not until the fire snaps a second time that you jump and remember to ask for an egg.  The fire seems to consider your request for a moment before an Aries egg jumps out of the fire, landing squarely in front of you.'),
	(39, 4, 'App\\Models\\Item', 37, 'Refreshing Mix', 6, 'The Refresh Potion restores a little bit of your combat, training, and exploring energy.', 'You mix the potions and the components to obtain a new potion.'),
	(40, 4, 'App\\Models\\Item', 39, 'Moxious Magic', 6, 'The Moxie Potion will restore some of your combat energy, up to 15 points.', 'You mix the potions and the components to obtain a new potion.'),
	(41, 4, 'App\\Models\\Item', 40, 'Vitamin V', 6, 'The Vitality Potion will restore some of your training energy, up to 25 points.', 'You mix the potions and the components to obtain a new potion.'),
	(42, 4, 'App\\Models\\Item', 38, 'Vigorous Mix', 6, 'The Vigor Potion will restore some of your exploring energy, up to 25 points.', 'You mix the potions and the components to obtain a new potion.'),
	(43, 6, 'App\\Models\\Creature', 336, 'Dendros Egg', 1, 'This is a quest only available to those who have 400 or more accomplishments.  To seek out the wisdom of the Life Tree, you must go on a quest to seek out four ancient components: Mystic Dew, found in the Great Plains and Sargasso; Gemstones, found in New Atlantis and Old City; Tree Seeds, found in Silva and Life Tree and Spirit Stones, found in the Mountains and Red Sand.  After acquiring 100 of each of these, as well as nutrients in the form of 50 component bags, you may return here to create a rare Dendros egg.', 'A swirling blast of magic fills all of your vision, swarming you with colors you can\'t even describe. You can feel so much power and wisdom surging through your mind that you can hardly believe it. It overwhelms you. You wake up, wondering how long you were out, and keep trying to remember everything you had learned, but the knowledge can be grasped no better than the wind. You find a Dendros egg waiting beside you.'),
	(44, 5, 'App\\Models\\Creature', 341, 'Earth Spell', 1, 'An ancient Druid spell summons calls forth a Taurus egg from the earth.', 'This looks to be a time-consuming ritual, but you were told to follow the directions precisely.  Crushing the components together, you boil the starweave and treescent until the stew turns turquoise.  When you add the ancientberry, it turns brown at first but you wait until it\'s emerald.  Sprinkling the bluemaple on top, you wait for the potion to cool and bring it out to a patch of earth.  You pour it in the shape of the designated symbol and wait.  Slowly, flowers creep from where you the mixture met the earth and when they flourish, you see a Taurus egg waiting for you.'),
	(45, 5, 'App\\Models\\Creature', 356, 'Two for One', 1, 'This spell summons the power of the wind and upon giving it voice, results in a pair of Gemini eggs.', 'It takes you time, but eventually you manage to produce enough wind chimes for the spell.  You take care to hang them in the clearing in two neat rows and stand between them to whisper the incantation.  The spell paper\'s whipped away by the sudden swell of wind but you stay still, and you find yourself caught between two opposing gusts of wind. The chimes clash loudly, but you think you hear voices.  They\'re discordant at first but you think they\'re trying to find a harmony; finally, they mesh into a tune, and you find Gemini eggs tightly bound together in front of you.'),
	(46, 5, 'App\\Models\\Creature', 384, 'Night at Home', 1, 'When cast in the proper setting, this spell summons a Cancer egg.', 'You know you need to set this spell up properly, so you\'re especially careful and wait for the concoction to fully boil.  When it does, it turns red and you dip the stones in.  They\'re translucent when you pull them out, and you set them about the room, adjusting the light so the entire area glows red.  Setting out a bowl of water, you sit in front of it and recite the spell, then close your eyes to wait patiently.  Finally, you hear a small splash and when you open look, you see a Cancer egg testing the water with a little leg.'),
	(47, 5, 'App\\Models\\Creature', 392, 'Caught Sunlight', 1, 'On a bright sunny morning, this spell can summon a Leo egg.', 'You wait until you hear the day will be clear, then trek outside to the highest stable surface you can find.  There, you set up the metal so it catches the sunlight and focuses it onto the pile of components.  You whisper the words and after some time, they seem to catch alight.  It\'s blindingly bright but you try not to hesitate, and follow the next step, putting your hands in the light.  You feel a weight land abruptly in your palms and when you pull them back, you see a Leo egg resting, its tail twitching eagerly.'),
	(48, 5, 'App\\Models\\Creature', 404, 'Housecleaning', 1, 'One must reorganize their surroundings to summon a Virgo egg.', 'You read the directions Hephasteus wrote out and after reading the spell, start following them to a tee. First, you reorganize your books, magazines, and letters; you end up needing to build a few new shelving units, and try to make room for them.  Afterward, once the clutter\'s gone, you start cleaning.  It takes you a few hours, but at the end, everything looks spotless. There\'s a surge of magic by the components and you feel like you\'re being watched; when you turn, you see a Virgo egg perched atop one of your brand-new shelving units.'),
	(49, 5, 'App\\Models\\Creature', 422, 'All the Sides', 1, 'The summoner must build a suitable perch for a Libra egg.', 'After you find the most elevated location nearby, you set down your materials infused with a blend of components, and start building.  As you lay out the base and work your way up, you think about how much you want to summon this egg, but of course, you recognize it\'ll make you busier too.  Soon, a tall triangular shaped structure tapering to a very narrow point rests before you and when you step back, you see a Libra egg balancing at the very top, its chains jangling while it watches you with interest.'),
	(50, 5, 'App\\Models\\Creature', 437, 'Solitude', 1, 'Take a day to yourself to call a Scorpio egg.', 'You take your components and go to the most secluded area by the water that you can find.  Kneeling at the water\'s edge, you drop the components in and recall the words of the spell, reciting them out loud.  The water stops running, growing still and deep.  You look into the suddenly murky depths, and your thoughts drift to how you were before, and the new insights you\'ve garnered since.  It takes a moment for you to notice the glow in the water, and the forceful presence beneath the surface. You reach into the water and pull out a Scorpio egg.'),
	(51, 5, 'App\\Models\\Creature', 443, 'The True Path', 1, 'Corral fire to summon a Sagittarius egg.', 'You study the diagrams you received from Hephasteus and start building a stone maze.  You don\'t follow the directions exactly, but you go where your creativity takes you, arranging the ingredients.  When you\'re done, you light a match and it ignites, fire entering the maze and blazing forward like it has a mind of its own.  It rails against the stone boundaries and you wonder if it\'ll reach the center, but decide to be patient.  In the end, the flame takes a twisted path, but roars when it reaches the center.  The light shifts purple and when it dies down, you find a Sagittarius egg in the embers.'),
	(52, 5, 'App\\Models\\Creature', 456, 'Fires of Friendship', 1, 'This spell summons forth a small well of lava that, upon receding, leaves behind a Garnet egg.', 'You head out to the middle of the desert in search of the 15 desert warmed stones you need to make your summoning circle. When you finally have your circle made, you pull out the rest of your things. You put the dried Essentia twigs in the circle then place your pile of moonrubies on top. You use the torch to light the twigs then sit back and think about all your current friendships. One by one, their faces appear in the flames.  The moonrubies began to melt and lava starts to bubble up from the ground.  When it dries, it crumbles away to reveal a Garnet egg.'),
	(53, 5, 'App\\Models\\Creature', 468, 'River of Dreams', 1, 'This spell allows the caster to briefly enter the spirit world and bring back a single Amethyst egg.', 'Sitting in your boat, the current of the river slowly pulls you along. Mounted on the bow is a bowl that looks like a turtle shell - inside, burns incense made from powdered components. The fragrance is light and dreamy. You place a Time Warp Watch in the bowl and watch as the smoke grows like rolling fog. Vague shapes form just out of view, a few of which look familiar, like things you know you\'ve seen in dreams. You see something that is almost tangible and reach out yo grab it. An Amethyst egg. Upon that realization, the smoke clears and you find yourself once again back in the waking world.'),
	(54, 5, 'App\\Models\\Creature', 480, 'Limpid Depths', 1, 'Easier than a deep dive into the cavernous waters below Old City, this spell entices an Aquamarine egg to swim to your side.', 'Non-swimmers, take heart! Fortunately, this spell eliminates the need for any diving skill. Since all Aquamarines are masculine, the primary ingredient of this spell is the Male Gen-X Potion. Before the magic happens, you must first thoroughly grind the other ingredients with mortar and pestle, then mix with waters from the Old City caverns (the purest waters found on Esmelda, by the way). Heat carefully, boiling until the components dissolve and the mixture is crystal-clear; add the Gen-X potion. The magic of Esmelda simulates the chill of the caverns deep underground without having to be there, and somehow through that magic, as the mixture cools, inside your cooking pot coalesces a perfect Aquamarine egg!'),
	(55, 5, 'App\\Models\\Creature', 492, 'Pressure', 1, 'This spell allows the caster to call forth a flawless crystal and magically apply enough pressure to crack it open to reveal a Diamond egg.', 'You place all your supplies on the desk in front of you and take a deep breath. Dipping your pen into the magic ink, you begin to draw. Concentrating, you draw several complicated glyphs. As you stretch your cramped hand, wondering if you drew them properly, the glyphs begin to glow. The light grows brighter and brighter.  When it fades, you find a large crystal sitting before you. Slowly, it begins to crack and its once flawless surface is now filled with hundreds of hairline fractures. The crystal explodes in a glittering rain of light and now before you is a shining Diamond egg.'),
	(56, 5, 'App\\Models\\Creature', 503, 'Crystalline Emergence', 1, 'Although they are challenging to locate, this spell summons forth the elusive Emerald egg.', 'You arrive in Old City, determined to find the egg possibly rarer than a Diamond. Finding a suitable building foundation, you build a small stone pyramid as suggested in the secret recipe. To obtain the proper brilliant green hue, you mix the Whiteroot with the Watervine, then carefully fold in the highly prized Ancientberries and Essentia. Slathering this concoction over the pyramid, you wait patiently; nothing happens. Re-reading the recipe desperately, you notice some previously overlooked small print. “The secret word is ‘Smeralda’!” You close your eyes and prayerfully mutter this strange word. When you open your eyes, before you sits an Emerald egg!'),
	(59, 5, 'App\\Models\\Creature', 519, 'Lustrous Essence', 1, 'From the Binary River of data and one contrary misplaced byte, this spell triggers transmutation of a lovely pearlescent egg.', 'Although Esmelda lacks an “information superhighway,” you must immerse yourself in Old City’s Binary River to begin this spell. Eventually, you sense a single byte of data that has decided to go against the flow. Capturing this maverick “seed,” you surround it with the requisite components and then freeze all of the materials with the Cryogenic Spray. Soon, almost subliminally, you sense a constant, soothing hum emanating from the materials. Daily the hum grows louder until one day you see that a crack has formed in the frozen mass and a soft pinkish light is seeping out. Carefully peeling off the outer shell, you are thrilled to uncover a lustrous Pearl egg!'),
	(60, 5, 'App\\Models\\Creature', 452, 'Lead to Gold', 1, 'An alchemical formula used to create a Bastet egg.', 'Walking into Hephasteus’s alchemy lab, you fire up the burner, eager to get started. You spread the parchment on the table, gathering the needed supplies from the shelves. Carefully, you combine the powdered components and add the Gen-X. You place the beaker of components on the burner, stirring until it’s a rolling boil. When it’s done, you pour the liquid over several small pieces of lead. They melt together, and then slowly start stretching as it comes to life. You place the sunnyseed in the middle of the mass and it wraps around the seed, forming into the shape of an egg. When it’s all over, a golden Bastet egg sits before you.'),
	(61, 5, 'App\\Models\\Creature', 541, 'Up, Up and Away', 1, 'Learn to observe to summon a Ruby egg.', 'The instructions were simple: "Find the highest place you can and observe."  What better place than an Old City hover balloon?  Looking out across Esmelda, you see a large group of Manos honing their electroreceptive sense.  Some Flamencos fly by and land, starting an intricate dance routine with a bunch of Lamiels.  A herd of Relity gallops though the sand dunes of Red Sand, kicking up a cloud of dust.  Suddenly, you realize you\'re not alone.  A furry Ruby egg has appeared next to you, seemingly watching with you.  When the music and dancing end, you take the balloon out of hover mode and start the journey home.'),
	(62, 5, 'App\\Models\\Creature', 545, 'Epiphany', 1, 'A sudden burst of inspiration that results in a Peridot egg.', 'You walk into Hephasteus\' back room, perplexed by his instructions: "Bring a project you’ve had trouble with." You spread out notebooks and half-completed models, shaking your head.  Suddenly, a small glitter of light flits outside your vision - it\'s there, and then it\'s not.  The light continues bouncing around and you watch, mesmerized by its seemingly random movements.  Looking at your things again, you can see all the inner workings of your invention; feverishly, you record your thoughts and complete the model. You sit back, looking at the work that had stumped you for months, and smile. The tiny pebble-sized light comes to a stop atop your model, and you realize it’s a Peridot egg.'),
	(63, 5, 'App\\Models\\Creature', 553, 'Striations of Sand, Sea and Sky', 1, 'By answering the call of the sea, this spell allows you to discover a Sapphire egg.', 'Ah, the gentle susurration of the ocean! It speaks to you; it is part of who you are. It calls your name whether you are at the water’s edge or miles inland. One particularly sunny day, you find yourself irresistibly drawn to the edge of the Sargasso Sea. Standing barefoot as the waves lap and the sand shifts beneath your feet, you observe the clouds on the distant skyline. There\'s one that looks like an Echo!  That one near it looks positively Brody-esque; what fun!  A strange movement beneath your feet draws your attention. How did that Sapphire egg get there? You thought they were native to Old City!'),
	(64, 5, 'App\\Models\\Creature', 565, 'Rainbow Shimmers', 1, 'The colors of a rainbow coalesce to form an Opal egg.', 'As a member of the Explorers\' Guild, much of your life is spent spelunking in the twilit caverns of Old City. Inevitably, however, even you occasionally yearn for the feeling of the sun, wind and rain on your face.  A particularly changeable Esmeldan day seems perfect for your "walkabout," and you set out for a pleasant walk in the rain. As the rain tapers off, the sun breaks through and warms everything around you. Ahead of you appears a rainbow. You notice a young Patrick sitting near the rainbow’s end with a pot of something in front of him. Instead of gold, however, you are delighted to find a shimmering Opal egg inside the pot.'),
	(65, 7, 'App\\Models\\Creature', 719, 'Elemental Fire', 1, NULL, NULL),
	(66, 8, 'App\\Models\\Consumable', 29, 'Earth Orb', 1, NULL, NULL),
	(67, 8, 'App\\Models\\Consumable', 30, 'Fire Orb', 1, NULL, NULL),
	(68, 8, 'App\\Models\\Consumable', 31, 'Water Orb', 1, NULL, NULL),
	(69, 8, 'App\\Models\\Consumable', 32, 'Wind Orb', 1, NULL, NULL),
	(70, 8, 'App\\Models\\Consumable', 33, 'Earth Shards', 4, NULL, NULL),
	(71, 8, 'App\\Models\\Consumable', 34, 'Fire Shards', 4, NULL, NULL),
	(72, 8, 'App\\Models\\Consumable', 35, 'Water Shards', 4, NULL, NULL),
	(73, 8, 'App\\Models\\Consumable', 36, 'Wind Shards', 4, NULL, NULL),
	(74, 9, 'App\\Models\\Creature', 298, 'Capricious Egg', 1, 'A wooly puff of an egg with wings and dragon horns.', NULL),
	(77, 7, 'App\\Models\\Creature', 750, 'Elemental Wind', 1, 'This spell gives form to the formless.', NULL);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
