name: uc-archive
services:
  laravel:
    build:
      context: .
      dockerfile: .docker/nginx.prod.Dockerfile
      args:
        PHP_VERSION: 8.2
    ports:
      - ${APP_PORT:-80}:8080
    depends_on:
      - php
      - db
    volumes:
      - web_content:/var/www/html
    networks:
      - internal
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: .docker/php.prod.Dockerfile
    volumes:
      - web_content:/var/www/html
    networks:
      - internal
    restart: unless-stopped

  db:
    image: mariadb:lts
    environment:
      #MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: 'pass'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:

volumes:
  web_content:
  db_data:
