services:
  app:
    build:
      context: .
      target: dev
    ports:
      - 5173:5173
    networks:
      - internal
    volumes:
      - ./app:/var/www/app
      - ./config:/var/www/config
      - ./routes:/var/www/routes
      - ./settings:/var/www/settings
      - ./database:/var/www/database
      - ./public/images:/var/www/public/images
      - ./storage:/var/www/storage
      - ./lang:/var/www/lang
      - ./resources:/var/www/resources
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./package.json:/var/www/package.json
      - ./package-lock.json:/var/www/package-lock.json
      - ./vite.config.js:/var/www/vite.config.js
      - ./.env:/var/www/.env
      - ./node_modules:/var/www/node_modules
      - .docker-contents/php.ini:/etc/php/8.4/fpm/php.ini
      - appdata:/var/www/storage
      - web_content:/var/www

  nginx:
    image: nginxinc/nginx-unprivileged:1.28-alpine-slim
    ports:
      - 80:8080
    depends_on:
      - app
      - db
    networks:
      - internal
    volumes:
      - .docker-contents/nginx.conf:/etc/nginx/conf.d/default.conf
      - web_content:/var/www

  db:
    image: mariadb:10.9
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

networks:
  internal:

volumes:
  web_content:
  db_data:
  appdata:
