services:
  nginx:
    image: nginxinc/nginx-unprivileged:1.28-alpine-slim
    ports:
      - 80:8080
    depends_on:
      - app
      - db
    networks:
      - internal
    volumes:
      - .docker-contents/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public/images:/var/www/public/images
      - ./resources:/var/www/resources
      - web_content:/var/www

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    networks:
      - internal
    volumes:
      - ./app:/var/www/app
      - ./config:/var/www/config
      - ./routes:/var/www/routes
      - ./settings:/var/www/settings
      - ./database:/var/www/database
      - ./public:/var/www/public
      - ./storage:/var/www/storage
      - ./lang:/var/www/lang
      - ./resources:/var/www/resources
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./package.json:/var/www/package.json
      - ./package-lock.json:/var/www/package-lock.json
      - ./vite.config.js:/var/www/vite.config.js
      - ./.env:/var/www/.env
      - .docker-contents/php.ini:/etc/php/8.4/fpm/php.ini
      - appdata:/var/www/storage
      - web_content:/var/www

  db:
    image: mariadb:10.9
    ports:
      - 3306:3306
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  testnginx:
    image: nginxinc/nginx-unprivileged:1.28-alpine-slim
    networks:
      - test
    volumes:
      - .docker-contents/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public/images:/var/www/public/images
      - ./resources:/var/www/resources
      - web_content:/var/www

  testapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - testdb
    networks:
      - test
    volumes:
      - ./app:/var/www/app
      - ./config:/var/www/config
      - ./routes:/var/www/routes
      - ./settings:/var/www/settings
      - ./database:/var/www/database
      - ./public/images:/var/www/public/images
      - ./storage:/var/www/storage
      - ./lang:/var/www/lang
      - ./resources:/var/www/resources
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./package.json:/var/www/package.json
      - ./package-lock.json:/var/www/package-lock.json
      - ./vite.config.js:/var/www/vite.config.js
      - ./.env.testing:/var/www/.env
      - ./tests:/var/www/tests
      - ./ecs.php:/var/www/ecs.php
      - ./phpstan.neon:/var/www/phpstan.neon

  e2e-testapp:
    image: mcr.microsoft.com/playwright:v1.53.0-noble
    networks:
      - test
    tty: true
    volumes:
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./package.json:/var/www/package.json
      - ./package-lock.json:/var/www/package-lock.json
      - ./playwright.config.ts:/var/www/playwright.config.ts
      - /var/www/node_modules
      - /ms-playwright
      - ./tests:/var/www/tests

  testdb:
    image: mariadb:10.9
    networks:
      - test
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - testdb_data:/var/lib/mysql

networks:
  internal:
  test:

volumes:
  web_content:
  db_data:
  appdata:
  testdb_data:
