# grab composer 🎶
FROM composer:latest AS composer

FROM node:24.0-alpine3.21 AS node

FROM php:8.4-fpm-alpine3.21 AS base
WORKDIR /var/www
RUN apk update && apk add curl-dev oniguruma-dev libxml2-dev icu-dev
RUN docker-php-ext-install mbstring pdo mysqli pdo_mysql intl

FROM base AS dev
COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm

COPY app ./app
COPY bootstrap ./bootstrap
COPY config ./config
COPY database ./database
COPY public ./public
COPY resources ./resources
COPY routes ./routes
COPY storage ./storage
COPY package.json package-lock.json ./
COPY vite.config.js ./

RUN [ "npm", "ci" ]

COPY composer.json composer.lock artisan ./
RUN composer install --prefer-dist --no-scripts --no-progress --no-interaction --no-autoloader \
  && composer dump-autoload --optimize --apcu

RUN chmod -R 770 ./storage ./bootstrap/cache
RUN mkdir -p /var/www/storage/logs \
  && touch /var/www/storage/logs/laravel.log \
  && chown -R www-data:www-data .
